### ISSUE TITLE
Reconsider the name?

### ISSUE THREAD

**Issue by ncoghlan** [uranusjr/snafu#9]
This is a really cool project, and as an individual, I really like the current name :)

As a Python Packaging User Guide maintainer though, I'm far less keen on the idea of explaining to folks what SNAFU means (even though it's a thoroughly accurate description of the world of software distribution in general).

While I know it's less fun that way, would you be willing to consider a more boring name like `winpyenv` or `winpyrm`? (the latter would be short for "WINdows PYthon Runtime Manager")

**Comment by uranusjr** [comment]
I agree; the name was chosen half as an inside joke, and is suitable only as a personal project.

I personally really dislike pyenv’s name (the *env* part is so confusing), so that’s probably out. I’m fine `winpyrm` in general, but it sounds like we’re removing something (the *rm* part).

Some other possible directions…

* `pywinst` (does this miss the managing part?)
* `pywm` or `pwm` (”Python for Windows“ Manager)

**Comment by ncoghlan** [comment]
Unfortunately `wininst` is a bit confusing due to the old `bdist_wininst` format, and `pyinstaller` is similarly out due to the project that makes full Windows installers for Python projects.

`winpym` (for "WINdows PYthon Manager", pronounced "win-pim") would avoid the "rm" suffix, while `pym4win` ("PYthon Manager for WINdows") would avoid colliding with the existing (non-Python) program "WinPIM".

**Comment by uranusjr** [comment]
It occurred to me while working on [another similar tool](https://github.com/uranusjr/pym-macos) this is basically what `rustup` is to Rust. So… `pythonup`? Just throwing it out.

**Comment by ncoghlan** [comment]
`pythonup` could work - I'd originally discounted it due to https://pyup.io/, but https://www.google.com.au/search?q=pythonup looks promisingly empty.

And if you eventually expanded beyond Windows (e.g. by depending on pyenv), the name would still fit.

**Comment by uranusjr** [comment]
I think I’ll go with PythonUp then. I already built a similar tool for Mac (as a Homebrew Tap), and yes it is depending on pyenv (more specifically the bundled *python-build* plugin). :p

**Comment by uranusjr** [comment]
Tracking in #11.
